public: false
# If true, then exercise kernels synced to kaggle will have internet enabled and will begin
# with a cell that pip installs the current learntools branch. (Useful for testing 
# notebooks on Kernels without requiring image docker deploy for every learntools change)
development: true
